Rework questions
acmhack/registration-page pull request #5
Opened 2023-03-03 20:28 UTC by JasonXu314

2023-03-03 21:03 UTC, Cire15 requested changes
The changes are good, just a few things to comply with MLH.

2023-03-04 18:20 UTC, JasonXu314 commented on pages/application.tsx
> +										<TextInput
the dropdown was so big that opening it caused it to flash black, so we changed it to a free input with the note

2023-03-05 02:23 UTC, Cire15 commented on pages/application.tsx
> +										<TextInput
if they're cool with it, I'm cool with it

2023-03-05 02:26 UTC, Cire15 approved these changes
👍

2023-03-05 02:26 UTC, merged